### ISSUE TITLE
Why this happened ?

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#11]
Bro, good day or night ;)

Why resulted private key after dividing is bigger then a devided privkey ?

root@C.2635410:~/ecctools$ ./modmath 0x100000000000000000000000000000
0 / 30240                                                            
Result: 61cb720c761cb720c761cb720c761cb6a4811d64db34aaa77c3500a19c342
679

Ho to manipulate with keys for get result < then a 
0x100000000000000000000000000000 ??

Thanks !

**Comment by Hurd8x** [comment]
And this additional, why then divide to 7 and 6 I get BIIIG PRIVKEYS ?

oot@C.2635410:~/ecctools$ ./modmath 0x1000000000000000000 /  2      
Result: 800000000000000000                                           
                                                                     
root@C.2635410:~/ecctools$ ./modmath 0x1000000000000000000 /  4      
Result: 400000000000000000                                           
                                                                     
root@C.2635410:~/ecctools$ ./modmath 0x1000000000000000000 /  6      
Result: 55555555555555555555555555555554e8e4f44ce5183593ea9b74d99abcc
06b                                                                  
                                                                     
root@C.2635410:~/ecctools$ ./modmath 0x1000000000000000000 /  7      
Result: 49249249249249249249249249249248c79facd43214c035a4853f95f258a
4ee                                                                  
                                                                     
root@C.2635410:~/ecctools$ ./modmath 0x1000000000000000000 /  8      
Result: 200000000000000000                                           
                                                                     
root@C.2635410:~/ecctools$

**Comment by albertobsd** [comment]
All those results are correct.

Only exact divisions get a Lower number than the original divided key.

Why this happened because all the divisions are a multiplication by the inverse mod N

**Comment by Hurd8x** [comment]
Thanks
