### ISSUE TITLE
Ubuntu compile error ?

### ISSUE THREAD

**Issue by liodragon** [albertobsd/ecctools#12]
Hello Alberto,
Any suggestion about error that I'm get as response , please? Thnx in Advance...

~/ecctools$ sudo make
gcc -O3 -c bloom/bloom.c -o bloom.o
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
gcc -O3 -c gmpecc.c -o gmpecc.o
gmpecc.c:1:10: fatal error: gmp.h: No such file or directory
    1 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:7: default] Error 1

Update:
I'm on Win WSL - so after install $ sudo apt install libcrypt-dh-gmp-perl
also received same error response after "make"

**Comment by CookLand** [comment]
sudo apt install libgmp-dev

**Comment by liodragon** [comment]
ThnX a loOOOot
