### ISSUE TITLE
Make please additional function to ./keymath and ./modmath ?

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#13]
Bro, then try calculate some more difficult for ex divide pubkey + multiply key to number + add to pubkey a number needs paste previous result(from 1, 2, 3 operation etc). 

Can you add function for calculate many math operation then just one run ? For ex after publick key add MANY needed operation and calculate for ex:

./keymath 03a301697bdfcd704313ba48e51d567543f2a182031efd6915ddc07bbcc4e16070 / 4 , x 6 , + 1, /6   , + 10, x 3, / 8 etc ???

./modmath 1233456fffeeecc / 4 , x 6 , + 1, /6   , + 10, x 7,+4, / 1 etc ???
Please Bro ?

This function will be very helpful.

Please Bro ?

Thank You

**Comment by albertobsd** [comment]
You can learn some basic bash and redirect the output of the program to a bash variable and do the operations with the variables in a bash file.

if you like my work please make a good donation and maybe I will considerate make the program to do multiple operations in the way that you want.

Regards!

**Comment by hitendrapharmacy** [comment]
./ modmath 10 / 2 gves result in HEX so can you please Add DECIMAL function on result too ...!!
So result have both HEX and DEC.

**Comment by albertobsd** [comment]
you can edit it. Copy and paste the line of the result and edit it to show the result in decimal instead of hex, it only need to change one character.

**Comment by albertobsd** [comment]
for mothmath add the next line:

```
gmp_printf("Result: %Zd\n\n",C);
```
just before of the line 87

```
gmp_printf("Result: %Zx\n\n",C);
```

the code will look like:

```
gmp_printf("Result: %Zx\n\n",C);
gmp_printf("Result: %Zd\n\n",C);
```
