### ISSUE TITLE
./modmath

### ISSUE THREAD

**Issue by hitendrapharmacy** [albertobsd/ecctools#14]
Hi ./ modmath givinf result in HEX value...can you please make it in HEX and DEC or Can we able to choose weather its HEX or DEC please?

**Comment by albertobsd** [comment]
for mothmath add the next line:

```
gmp_printf("Result: %Zd\n\n",C);
```
just before of the line 87

```
gmp_printf("Result: %Zx\n\n",C);
```

the code will look like:

```
gmp_printf("Result: %Zx\n\n",C);  //Hexadecimal '%Zx'
gmp_printf("Result: %Zd\n\n",C); //Decimal '%Zd'
```
