### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by hitendrapharmacy** [albertobsd/ecctools#15]
please resolve ./modmath result to HEX and DEC

**Comment by albertobsd** [comment]
for mothmath add the next line:

```
gmp_printf("Result: %Zd\n\n",C);
```
just before of the line 87

```
gmp_printf("Result: %Zx\n\n",C);
```

the code will look like:

```
gmp_printf("Result: %Zx\n\n",C);  //Hexadecimal '%Zx'
gmp_printf("Result: %Zd\n\n",C); //Decimal '%Zd'
```

Edit the code, I don't know why you want the result in Decimal, no one software accepts keys in Decimal, all use Hexadecimal or WIF format

**Comment by hitendrapharmacy** [comment]
got it thanks brother
