### ISSUE TITLE
Possible to add pubkey?

### ISSUE THREAD

**Issue by hitendrapharmacy** [albertobsd/ecctools#17]
is that possible to add compress pubkey to ./modmath 10/2 result : DEC HEX Pubkey?

**Comment by albertobsd** [comment]
Modmath is exclusively for Numbers, the reason for modmath is to give you some idea where are the result of private keys after  begin divided for a non exact divisor, examples: 3/2 , 1/2, 5/3  etc...

if you want to know the public key of the result, just use it in ./calculatefromkey <keyhere>

example

```
albertobsd $ ./modmath 5 / 3
Result: 55555555555555555555555555555554e8e4f44ce51835693ff0ca2ef01215c2

albertobsd $ ./calculatefromkey 55555555555555555555555555555554e8e4f44ce51835693ff0ca2ef01215c2
privatekey: 55555555555555555555555555555554e8e4f44ce51835693ff0ca2ef01215c2
publickey compressed: 033de60cc3848de4f435008e2daa73efd2a52d03c8dd771f43dc77162cc37d38dd
public address compressed 12Avix6KrdFE1oyMedHDnCE7ZsuwUS6XX8
publickey uncompressed: 043de60cc3848de4f435008e2daa73efd2a52d03c8dd771f43dc77162cc37d38ddd591ef1a1de3c4d984702f7ad7be6c22537575cdee7aabf4a2e49e6a9a281641
public address uncompressed 1JzDgrQT8czVvyff7UUChRpSDsT1VokKte
````

And another thing, why you want the publickey also in Decimal? Are you working with another program? If that is the case please tell me what program is it, depending on that i can make something for it.

**Comment by hitendrapharmacy** [comment]
Thank You..I was trying to do some research on numbers.........

**Comment by Hurd8x** [comment]
> 

Hi. Decimal is more accurate in calculation but not so good like hex in viewing.

Can you add making shared pubkey from pukeys only ? This interesting then operate fake point with non standard order or coordinates for example.

Bro, and think time to make editable base point and order of a curve  in keymat, modmath, keyyadd, and shared pubkey. What you think about this ?

Br
