### ISSUE TITLE
"bash: ./keysubtracter: No such file or directory" why?

### ISSUE THREAD

**Issue by ahnuo** [albertobsd/ecctools#18]
Dera Alberto,please help me !
"bash: ./keysubtracter: No such file or directory" why?

**Comment by albertobsd** [comment]
....

keysubtracter is in another repository.

https://github.com/albertobsd/keysubtracter

**Comment by ahnuo** [comment]
like this 

ahnuo@DESKTOP-94OD6SC:~/ecctools$ make
gcc -O3 -c bloom/bloom.c -o bloom.o
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
#gcc -O3 -c gmpecc.c -o gmpecc.o
gcc -O3 -c util.c -o util.o
gcc -O3 -o rehashaddress rehashaddress.c gmpecc.c util.o sha256.o base58.o rmd160.o -lgmp
gcc -O3 -o calculatefromkey calculatefromkey.c gmpecc.c util.o base58.o sha256.o rmd160.o -lgmp `libgcrypt-config --cflags --libs`
/bin/sh: 1: libgcrypt-config: not found
calculatefromkey.c:18:10: fatal error: gcrypt.h: No such file or directory
 #include <gcrypt.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
ahnuo@DESKTOP-94OD6SC:~/ecctools$ ./keymath
-bash: ./keymath: No such file or directory
ahnuo@DESKTOP-94OD6SC:~/ecctools$ ./keymath 02ceb6cbbcdbdf5ef7150682150f4ce2c6f4807b349827dcdbdd1f2efa885a2630 / 4
-bash: ./keymath: No such file or directory

**Comment by albertobsd** [comment]
Tip: always read the instructions even if your plan is not follow them, this apply to all the instructions in the life.

Read the documentation please there are some steps to install the dependencies needed to compile the code correctly.
