### ISSUE TITLE
How to limit the number of decimal numbers obtained during calculation and used in calculations ?

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#19]
Good day.

Then I use keymath and modmath  and devide for deviding for example 777 / 999 = 0.77777777777777777....7 inf. modmath and keymath genererate result not with minimum needed float numbers 0.77777777777777777(This will be named X) *  999 = 777.0, but with maximum nposible float number - 0.777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777 ........7 (this will be named Y) * 999 = 777.0 and  private / publick keys for X and Y are different !!!

How to use in calculus editable floats count in result ?
Bro, help plesse ?

**Comment by albertobsd** [comment]
What are you talking about?

There aren't decimal point numbers in ECC.

**Comment by Hurd8x** [comment]
Privkey 3333 / 600000  has decimal 0.005555 

And privkey from 3333/600000 = cb21d53cddd6e04c059210385c67dfe227e40e82db50152607c41e2ce78aead6

How to round  3333/600000 from   0.005555 to 0.0055 ?
