### ISSUE TITLE
rehashaddress Support for entering password from text？

### ISSUE THREAD

**Issue by zhanshen360** [albertobsd/ecctools#2]
rehashaddress Support for entering password from text，So you can enter multiple passwords！
And the output can specify only print mode，Like below：
Address only
1QLJY8Ep5WWwwoxPFjhNaqWTo7CYUhCfn1
1BFpD2RWHH4byetSdxou5x4cjSioyDR4uc
Private key only
5141853d88d49186ca8de96107e64a1464469da20b1f18d5116fe94bb9c80d99
b62f7b4c940282aae1f3370c0c0cf9d47cf82e2f0d4e8f9fa9f3694d9afa8804
Compressed public key only
020f085d02b5a1230655f4acb00ce3fda60306f20d4260c7e0100c8378d916e778
02436850d41bcaddf94a149a74ae4f2f5c155f9e0f30ef6f788238171018b8bf62
Uncompressed public key only
040f085d02b5a1230655f4acb00ce3fda60306f20d4260c7e0100c8378d916e778430675ac64f252340764620f576dba0ed5ea5106304948949306ba78dec761a0
Print all
5141853d88d49186ca8de96107e64a1464469da20b1f18d5116fe94bb9c80d99
020f085d02b5a1230655f4acb00ce3fda60306f20d4260c7e0100c8378d916e778
1QLJY8Ep5WWwwoxPFjhNaqWTo7CYUhCfn1
040f085d02b5a1230655f4acb00ce3fda60306f20d4260c7e0100c8378d916e778430675ac64f252340764620f576dba0ed5ea5106304948949306ba78dec761a0
1BFpD2RWHH4byetSdxou5x4cjSioyDR4uc

**Comment by albertobsd** [comment]
Interesting, maybe I add another program to do that.

Did you want the simplified output to pass it to another script?

**Comment by zhanshen360** [comment]
Yes, Thanks
