### ISSUE TITLE
Why this method not work on puzzle privkeys ? p.s. dividing...

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#21]
Hi

Loock:
we have pubkey of this privkey - 0xfffffffffffffffffffffffff

./md 0xfffffffffffffffffffffffff / 0x4000000000000
Result: 80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f9b463c06987c4

./md 0x80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f9b463c06987c4 - 0x4000000000000
Result: 80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f5b463c06987c4

xman@localhost:~/ecctools$ ./md 0x80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f5b463c06987c4 x 0x4000000000000
Result: fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

xman@localhost:~/ecctools$ ./md 1 - 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

Result: 2 this is a privkey what belong to pubkey, what we will brute - privkey 2.

we was find orivkey 2, and now we recover this privkey 
0xfffffffffffffffffffffffff

./md 1 - 2
Result: fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

xman@localhost:~/ecctools$ ./md 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 / 0x4000000000000
Result: 80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f5b463c06987c4

./md   0x80266a9dd3b03fffffffffffffffffff5d269cebf99579e8f2f9b463c06987c4      x         0x4000000000000                    Result: fffffffffffffffffffffffff

succesfuly recovered.

why method not work with puzzle priv/pubkey ?
I try many times but not succesful.

????

**Comment by albertobsd** [comment]
Because we don't know the real value of the puzzles.

You are only doing circles with values that you already know.

**Comment by Hurd8x** [comment]
> Because we don't know the real value of the puzzles.
> 
> You are only doing circles with values that you already know.

Bro, with know priv of puzzle not work.
What can you say about 2^100 puzle ? privkey known - 0xaf55fc59c335c8ec67ed24826 , what can yoy say about div this puzzl to 2^50 ?

**Comment by albertobsd** [comment]
I don't know what you try to achieve.

Please use this section to report bugs of the code no to ask your doubts about how to solve this or that
