### ISSUE TITLE
calculatefrompublickey from file

### ISSUE THREAD

**Issue by bigvito19** [albertobsd/ecctools#22]
Can you make it where it can do it from a file like this does https://github.com/albertobsd/ecctools#addr2rmd to address or rmd160.

I also notice you have https://github.com/albertobsd/ecctools#calculatefromkey and https://github.com/albertobsd/ecctools#calculatefrompublickey but both are the same

**Comment by Fgghjjghjnj** [comment]
Hi Alberto.


Key math is an arithmetic calculator for public keys, containing only four operations:

-addition
-subtraction
-multiplication by a scalar number
-division by a scalar number

It would be fantastic if we could do these operations "Key math" performed from the "input file.txt" and saved in "output файл.txt ". Let's say we specified one of the four operations (x / + - ) according to which the number "35" or another number will be calculated, then "Key math" we perform this operation with each line from the "output файл.txt ".

**Comment by albertobsd** [comment]
you can use bash or python to do that.
