### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fgghjjghjnj** [albertobsd/ecctools#23]
Hi Alberto.

Key math is an arithmetic calculator for public keys, containing only four operations:

-addition
-subtraction
-multiplication by a scalar number
-division by a scalar number

It would be fantastic if we could do these operations "Key math" performed from the "input file.txt" and saved in "output файл.txt ". Let's say we specified one of the four operations (x / + - ) according to which the number "35" or another number will be calculated, then "Key math" we perform this operation with each line from the "output файл.txt ".

**Comment by albertobsd** [comment]
Please use bash or python to do that
