### ISSUE TITLE
Alberto, help please ? ecctools qeschion. asap. help wanted

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#24]
I was change a N from order.SetBase16("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141") to 2^70

I divide 0xf56926f9ca9abc1065153d25383e80 / -1
Result: 20212ef8c52b3a842d0bc

but then I divide pubkey from

0xf56926f9ca9abc1065153d25383e80 - privkey;

pubkey  ./calculatefromkey f56926f9ca9abc1065153d25383e80
privatekey: 0000000000000000000000000000000000f56926f9ca9abc1065153d25383e80
publickey compressed: 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c

i gent NOT PUBKEY FROM  20212ef8c52b3a842d0bc

**029304ae3d06058417730a717b15727f651188448742442c311a5af9a5b02aa73d**

./calculatefromkey 20212ef8c52b3a842d0bc                               privatekey: 000000000000000000000000000000000000000000020212ef8c52b3a842d0bc
publickey compressed: **03193f6e2afc8e2a243239a25ec7c92807c07833bb66bcc63586ad1e1eadb79406**
public address compressed 13HzVpWa3YDVW9sEUEoc9wvJeMCZoCeDYb
publickey uncompressed: 04193f6e2afc8e2a243239a25ec7c92807c07833bb66bcc63586ad1e1eadb794062bcf9a0987701 bd2d1068a024f17c0edfe5f3cf7f7c3df74c2b2989d693c4bd3
public address uncompressed 1Hja51B5T5a2zHCTswdANGPDxYcju1hRQF

./keymath 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c / -1
Result: **029304ae3d06058417730a717b15727f651188448742442c311a5af9a5b02aa73d**

bupkey are differents, but must be pub1  = pub2 !!!

how to resolve this ?

ASAP.

Thank You

**Comment by Hurd8x** [comment]
03193f6e2afc8e2a243239a25ec7c92807c07833bb66bcc63586ad1e1eadb79406 not =  029304ae3d06058417730a717b15727f651188448742442c311a5af9a5b02aa73d

hot solve this bug ?

**Comment by albertobsd** [comment]
There is no division by a negative number in ECC,  that is the bug, I will add an restriction to avoid that.

**Comment by Hurd8x** [comment]
> There is no division by a negative number in ECC, that is the bug, I will add an restriction to avoid that.

Bro, how to make inverdion without -1 ? I try multiply, but not work:

./keymath 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c x -1
Result: 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c

?

Regsrds

**Comment by Hurd8x** [comment]
./modmath 0xf56926f9ca9abc1065153d25383e80 / 1180591620717411303423    Result: **be49e416089b9ef31de38**

./calculatefromkey f56926f9ca9abc1065153d25383e80                      privatekey: 0000000000000000000000000000000000f56926f9ca9abc1065153d25383e80
publickey compressed: **02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c**

./keymath  02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c / 1180591620717411303423
Result: **02f4f51aa66496ab1d7e685cfe4474d92d8b5dbd7698c371f4237ddaa2122b0311**

xman@localhost:~/7/ecctools$ ./calculatefromkey be49e416089b9ef31de38                               privatekey: 0000000000000000000000000000000000000000000be49e416089b9ef31de38
publickey compressed: **035e86aae702006a1f1216ccc96001cffc26c5c594bc9be0158647e08bb91fdd16**

pukey different again  

how to resolve this ?

Tnak you !

**Comment by albertobsd** [comment]
How do you compile the program. 
What is your environment. 
I run on Ubuntu WSL on Windows 10 and i get different results from the modmath division and my Resulting publickeys are the SAME, look:

![image](https://user-images.githubusercontent.com/17832765/185006250-aeefef76-c0e5-4ab0-8a01-832a8d280ab9.png)


```
albertobsd:~/ecctools$ ./modmath 0xf56926f9ca9abc1065153d25383e80 / 1180591620717411303423
Result: 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7

albertobsd:~/ecctools$ ./calculatefromkey 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7
privatekey: 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7
publickey compressed: 0267d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69d
public address compressed 1KYwqFVpE4aPCjxswbYoKyZWVmTkxzqnMv
publickey uncompressed: 0467d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69de609b4928a768250ad655bccd087a47f9af56cc09bbc4c7ea7b3678ef6bb7ac0
public address uncompressed 1Jj1UbW53AXgA6CWCWNHcjuCaho3cdJsxn
albertobsd:~/ecctools$ ./calculatefromkey f56926f9ca9abc1065153d25383e80
privatekey: 0000000000000000000000000000000000f56926f9ca9abc1065153d25383e80
publickey compressed: 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c
public address compressed 1DCfjcfiXLDfJPcs5BueSTfaHcv6GH7ZWJ
publickey uncompressed: 04470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c9974b94c6bc79b1d1a042d6891903c60aee337ceac5c1a60f1fa474677ba805e
public address uncompressed 19HN91w3x1M2bKC8A5r19RFUHhhcueCoRD
albertobsd:~/ecctools$ ./keymath 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c / 1180591620717411303423
Result: 0267d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69d
```

I think that you are using a buggy compiled version of my program. Please use Linux, not windows.

Regards!

**Comment by Hurd8x** [comment]
> How do you compile the program. What is your environment. I run on Ubuntu WSL on Windows 10 and i get different results from the modmath division and my Resulting publickeys are the SAME, look:
> 
> ![image](https://user-images.githubusercontent.com/17832765/185006250-aeefef76-c0e5-4ab0-8a01-832a8d280ab9.png)
> 
> ```
> albertobsd:~/ecctools$ ./modmath 0xf56926f9ca9abc1065153d25383e80 / 1180591620717411303423
> Result: 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7
> 
> albertobsd:~/ecctools$ ./calculatefromkey 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7
> privatekey: 259ca781781d06416496729e05e07418d5c68d69f794b3398768a7429ab581e7
> publickey compressed: 0267d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69d
> public address compressed 1KYwqFVpE4aPCjxswbYoKyZWVmTkxzqnMv
> publickey uncompressed: 0467d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69de609b4928a768250ad655bccd087a47f9af56cc09bbc4c7ea7b3678ef6bb7ac0
> public address uncompressed 1Jj1UbW53AXgA6CWCWNHcjuCaho3cdJsxn
> albertobsd:~/ecctools$ ./calculatefromkey f56926f9ca9abc1065153d25383e80
> privatekey: 0000000000000000000000000000000000f56926f9ca9abc1065153d25383e80
> publickey compressed: 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c
> public address compressed 1DCfjcfiXLDfJPcs5BueSTfaHcv6GH7ZWJ
> publickey uncompressed: 04470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c9974b94c6bc79b1d1a042d6891903c60aee337ceac5c1a60f1fa474677ba805e
> public address uncompressed 19HN91w3x1M2bKC8A5r19RFUHhhcueCoRD
> albertobsd:~/ecctools$ ./keymath 02470a635de37b909187e612e5aa853decbb9769416a2ecd055f990c1de501f66c / 1180591620717411303423
> Result: 0267d64ab89262eccc17b0671f0589786915c395aea89fb6ec3fca45f7b1bac69d
> ```
> 
> I think that you are using a buggy compiled version of my program. Please use Linux, not windows.
> 
> Regards!

Thank you your answer Bro.

I use N = 2^70, not N = 0xf.....141

this is a result with N = 2^70:
./modmath 0xf56926f9ca9abc1065153d25383e80 / 1180591620717411303423 Result: be49e416089b9ef31de38 - result mach smaler then yours....

your result with N = f....141.

try please on your machine this example wuth N = 2^70

?

please

Regaeds

**Comment by albertobsd** [comment]
>try please on your machine this example wuth N = 2^70

NO.

The N value should be FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141, any other value will give you always, wrong results.

**Comment by Hurd8x** [comment]
> > try please on your machine this example wuth N = 2^70
> 
> NO

unfortunatly 2^70 not work 

thank you very mach anyway....

Regards
