### ISSUE TITLE
Why then devide to 32 not work ?

### ISSUE THREAD

**Issue by Hurd8x** [albertobsd/ecctools#3]
I devide 62 bits pubkey to 32

And get this pubkeys:

03782e746d99acac63f8ef9fced1164cd55b20a28b1567ea34ce8dca4b0d890d40                                 
03666b5737758ddeb7bb98a95432cb81c58e9931e32b4b54ffa3b72faec6c33ba6                                 
03666b5737758ddeb7bb98a95432cb81c58e9931e32b4b54ffa3b72faec6c33ba6                                 
03782e746d99acac63f8ef9fced1164cd55b0a28b1567ea34ce8dca4b0d890d40                                  
03f231dc9ca5aa43b5bd96ad639b61a2348bf5918ca4a8ec79c9c4276deed78f8d

Result zero !! Nothin founded.

Albert, please help ?????

Regards.😭

**Comment by Hurd8x** [comment]
/keyhunt -m bsgs  -r 1:1000000000000  addresses.txt -q -s 10 -t
 40                                                                                                
[+] Version 0.2.211018 Chocolate _Beta!, developed by AlbertoBSD                                   
[+] Quiet thread output                                                                            
[+] Stats output every 10 seconds                                                                  
[+] Threads : 40                                                                                   
[+] Mode BSGS secuential                                                                           
[+] Opening file addresses.txt                                                                     
[+] Added 4 points from file                                                                       
[+] Range                                                                                          
[+] -- from : 0x1                                                                                  
[+] -- to   : 0x1000000000000                                                                      
[+] N = 0x100000000000                                                                             
[+] Bloom filter for 4194304 elements : 14.38 MB                                                   
[+] Bloom filter for 209716 elements : 0.72 MB                                                     
[+] Allocating 3.00 MB for 209716 bP Points                                                        
[+] processing 4194304/4194304 bP points : 100%                                                    
[+] Making checkums .. done                                                                        
[+] Sorting 209716 elements... Done!                                                               
                                                                                                   
End

**Comment by albertobsd** [comment]
The key division is some tricky, if the division is not exact the resulting public keys can be outside of your desire range. Put here you key and i will make the correct division to get one in some lower range.

Regards!

**Comment by Hurd8x** [comment]
Good Day Albert. This is my example:

original
0249a43860d115143c35c09454863d6f82a95e47c1162fb9b2ebe0186eb26f453f

- 1

03c71ba57f1265611a718690f8d7235feb9e0d505b962222a1112271c618bcf4b2

02.../ 62                                       
Result: 028b89bda008ae0ebe72dc7a1dbe0f5b4cf7299722fb1853477e5b6772810561d6

03...l/62

                                       
Result: 03666b5737758ddeb7bb98a95432cb81c58e9931e32b4b54ffa3b72faec6c33ba6

02 / 62 - 1

61d6 - 1                                        
Result: 03782e746d99acac63f8ef9fced1164cd55b0a28b1567ea34ce8dca4b0d890d40


3ba6 - 1                                        
Result: 03f231dc9ca5aa43b5bd96ad639b61a2348bf5918ca4a8ec79c9c4276deed78f8d

Show alghorithm how to devide fine Brother, pleease ,😭 

I not need a thousands of public keys 😭😭😭😭😭😭😭😭😭😭😭 Please Bro, how to do ???

**Comment by Hurd8x** [comment]
Albert, please downgrade this pubkey from 124 bytes to 62 bytes ?

0358c90b9357cdc0b16e8fdf97ed2bb7ae809e50d1de27a2934bc6a0fbad12ce5a

**Comment by kpot87** [comment]
And how do you know that this is 124bit ? You create them by yourself? And for what this key if it’s empty? 

@albertobsd and it will be great to see how you multiple the divided key. Thank you

**Comment by Hurd8x** [comment]
> And how do you know that this is 124bit ? You create them by yourself? And for what this key if it’s empty?
> 
> @albertobsd and it will be great to see how you multiple the divided key. Thank you

You succesfully devide any pubkeyb? What bitrange you divide ?

I not succesful with deviding and try many times.

Thank you.

**Comment by kpot87** [comment]
> > And how do you know that this is 124bit ? You create them by yourself? And for what this key if it’s empty?
> > @albertobsd and it will be great to see how you multiple the divided key. Thank you
> 
> You succesfully devide any pubkeyb? What bitrange you divide ?
> 
> I not succesful with deviding and try many times.
> 
> Thank you.

I just try one 60 bit to 58bit of 10 keys. Now will run bsgs to see if it fined or not

**Comment by Hurd8x** [comment]
> > > And how do you know that this is 124bit ? You create them by yourself? And for what this key if it’s empty?
> > > @albertobsd and it will be great to see how you multiple the divided key. Thank you
> > 
> > 
> > You succesfully devide any pubkeyb? What bitrange you divide ?
> > I not succesful with deviding and try many times.
> > Thank you.
> 
> I just try one 60 bit to 58bit of 10 keys. Now will run bsgs to see if it fined or not

Albert video is a strange, in one example then hi devide to /2, privkey range down from 8000000000000000 to 400000000000000, enoter example then he devide /2 so make 100% the same operation, privkey range down only to 1 bit !!!! And I try devide /2. .... not worked for me enfortunately...

**Comment by kpot87** [comment]
Can you give me a link for the video, haven’t seen

**Comment by Hurd8x** [comment]
> Can you give me a link for the video, haven’t seen

https://m.youtube.com/watch?v=crf9RVD8jl4&t=519s

**Comment by kpot87** [comment]
Ok let’s try make test together ? Present you pubkey and range

**Comment by albertobsd** [comment]
Ok guys just to clarify some things i start a discussion threads in the keyhunt repository:

https://github.com/albertobsd/keyhunt/discussions/136

**Comment by kpot87** [comment]
@Hurd8x had you divide successfully?

**Comment by Hurd8x** [comment]
> @Hurd8x had you divide successfully?

Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4....   3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys

**Comment by kpot87** [comment]
> > @Hurd8x had you divide successfully?
> 
> Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4.... 3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys

How many keys do you have at the end?

**Comment by Hurd8x** [comment]
> > > @Hurd8x had you divide successfully?
> > 
> > 
> > Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4.... 3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys
> 
> How many keys do you have at the end?

1

**Comment by kpot87** [comment]
> > > > @Hurd8x had you divide successfully?
> > > 
> > > 
> > > Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4.... 3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys
> > 
> > 
> > How many keys do you have at the end?
> 
> 1

You use key math or key divide?

**Comment by Hurd8x** [comment]
> > > > > @Hurd8x had you divide successfully?
> > > > 
> > > > 
> > > > Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4.... 3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys
> > > 
> > > 
> > > How many keys do you have at the end?
> > 
> > 
> > 1
> 
> You use key math or key divide?

Key math

**Comment by kpot87** [comment]
> > > > > > @Hurd8x had you divide successfully?
> > > > > 
> > > > > 
> > > > > Yes, but only to 4. Bat I had repiat divide - div to 4, div to 4, div to 4.... 3-4 times now, but for downgrade from 120 to 90 need 11 pcs for 4 dovede, but this is only one publick key not 2,3,4 or more publick keys
> > > > 
> > > > 
> > > > How many keys do you have at the end?
> > > 
> > > 
> > > 1
> > 
> > 
> > You use key math or key divide?
> 
> Key math

How is your theory of breaking 128bit? It’s not working? 120 and 125 puzzle still exist

**Comment by dry1515** [comment]
0358c90b9357cdc0b16e8fdf97ed2bb7ae809e50d1de27a2934bc6a0fbad12ce5a 

> Альберт, пожалуйста, уменьшите размер этого публичного ключа со 124 до 62 байт?
> 
> 0358c90b9357cdc0b16e8fdf97ed2bb7ae809e50d1de27a2934bc6a0fbad12ce5a

where did you get this public key and have a private from it urgently?
