### ISSUE TITLE
is there a way to use keygen with static privatekey

### ISSUE THREAD

**Issue by Dr-Shams** [albertobsd/ecctools#30]
is there a  way to use keygen for generating bitcoin address from static hexadecimal private key ??

**Comment by albertobsd** [comment]
I am not sure of  what is the purpose of that, did you mean like some kind of Seed value to generate deterministic wallets?

**Comment by Dr-Shams** [comment]
yes exactly , the program does marvelous job in creating random compination, and i wonder if it can do like what bitaddress website does , enetering a hexaedecimal value and getting the bitcoin address corresponding for it

**Comment by albertobsd** [comment]
I guess that you didn't read the documentation

There two tools that you can use for deterministic wallet generator.

One is rehash address, based on password (please use a difficult password)

https://github.com/albertobsd/ecctools#rehashaddress

and the other option is calculatefromkey

https://github.com/albertobsd/ecctools#calculatefromkey

Read the documentation of each those sections
