### ISSUE TITLE
calculate  incorrect method, Yes?

### ISSUE THREAD

**Issue by e20dra1974** [albertobsd/ecctools#31]
>>> 65096165055322767407827196705577385603448405744130176747093794104152547598903 / 2
32548082527661383703913598352788692801724202872065088373546897052076273799451L
>>> hex(32548082527661383703913598352788692801724202872065088373546897052076273799451)
'0x47f58fd70bfd4fb8f2ce893cbe246a6b9ac94b62c6866db80d886148f1bb911bL'
>>> hex(65096165055322767407827196705577385603448405744130176747093794104152547598903)
'0x8feb1fae17fa9f71e59d12797c48d4d7359296c58d0cdb701b10c291e3772237L'
./keymath  03c07a83ec106864885542bee448da450c7fe2ee5e64db514d4a408cc51faa6edf / 2
Result: 025f64958b1d0b25c6015ce6f76fd7fd15af5f53327c1f16408991f8b4f0de7419, ?

**Comment by albertobsd** [comment]
Keymath use eliptic curve operations and those operations are different from regular arithmetic.
