### ISSUE TITLE
What happens if when you divide an odd number like 43 

### ISSUE THREAD

**Issue by rage0920** [albertobsd/ecctools#32]
i tried dividing private key 2B (43) by 2  [03d528ecd9b696b54c907a9ed045447a79bb408ec39b68df504bb51f459bc3ffc9 -n 3 -d 2]

where the results are 

```
./keydivision -p 03d528ecd9b696b54c907a9ed045447a79bb408ec39b68df504bb51f459bc3ffc9 -n 3 -d 2
inversemultiplier : 7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1
0372032cac3177c280ceb3076d7f5104052413706c956ecf38acf410ada12473a6
0249f0c19658519bec46d379f05d5388bb3a97bb95fe366c636a6bd9b6e90eb946
02052b643cc9bfccf3b168fc7bf2f3fe6151598797641babf45e655e49c8937c66

```
what's happening can you please explain ?

**Comment by albertobsd** [comment]
The divisions on Eliptic curve aren't not like the division that we know.
In reality it is a multiplication for the inverse of the Dividend modulo N what this mean
Lets think in th division of 2/2 = 1 right?
Well in eliptic curve we need to find a X number that 2*X = 1 mod N

```N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141```

That X is the inverse value of 2

in this case: `0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1`

```
./modmath 0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1 x 2
Result: 1
```

So in your example you are multiplying 
```
( 0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1  x 43 ) mod N
0x157fffffffffffffffffffffffffffffe4adaf8d5fb89975049c2af0d37c8e7b0b mod N
0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20b6
```
you can do that operation in python
```
hex(0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1 * 43 % 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 )
```

The publickey of this number `0x7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20b6` is
`0372032cac3177c280ceb3076d7f5104052413706c956ecf38acf410ada12473a6`

That is your first value, you can calcualte the other values in the same way...

**Comment by rage0920** [comment]
Thank you so much..!!!
