### ISSUE TITLE
keymath multiplication

### ISSUE THREAD

**Issue by kemo159** [albertobsd/ecctools#36]
Hi alberto.
If i divided the pubkey and got the scalar number and find the new pubkey in keyhunt - how can i calculate the true privkey?

**Comment by albertobsd** [comment]
Lets to say that you divide ```X / 2 = Y```
and you found Y, now you want to get X.....
```Y * 2 = X```
  no???
welll is the same but in this case is mod N

```Y * 2 = X % N```
