### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by Noname400** [albertobsd/ecctools#4]
There are no good products in the software at the moment.  For bip 39 (BIP32, bip44) and also there are no good bip38 recovery products (this is very necessary.)
If you have the interest and time, the community will owe you a debt.
Thanks for your time and your efforts.
I am not an expert in c but wrote bip 32.44 to work in python.  This sparked interest in the community.
BIP 38 is interesting to me personally for restoring access to the wallet.
I will look forward to hearing from you.  Your products are unique

**Comment by Noname400** [comment]
Что скажете?

**Comment by albertobsd** [comment]
sorry for not reply before bro i was some busy, i will read the theory of those format to check what i can do.

Thanks!

**Comment by albertobsd** [comment]
I previously do some work for  bip38 and the main thing of "there is not good product" for that, is because the encryption is strong and one of the internals use scrypt  this is a difficult key derivation process for CPU and GPU that is why there is no good software for crack it.
