### ISSUE TITLE
Consecutive substraction

### ISSUE THREAD

**Issue by Pvnic** [albertobsd/ecctools#6]
Posting the same comment i left on Youtube ! :D

Hello alberto ! I wanted to know if it is possible to do substraction with the public key the same way it work with keydivision.
Fore exemple instead of  writing a line eache time i want to do a substraction with the result of the public key would it be possible to do like : ./keymath (publickey) - 1 -n (number of operations)
In short : Doing consecutive substraction or addition

**Comment by albertobsd** [comment]
The program Don't do that sorry maybe you can find a solution with bash script or something like that

**Comment by Totulik** [comment]
./keysubtracter -p 0290e6900a58d33393bc1097b5aed31f2e4e7cbd3e5466af958665bc0121248483 -n 8 -r 0:1
-n (number of operations)
https://github.com/albertobsd/keysubtracter

**Comment by Pvnic** [comment]
> ./keysubtracter -p 0290e6900a58d33393bc1097b5aed31f2e4e7cbd3e5466af958665bc0121248483 -n 8 -r 0:1 -n (number of operations) https://github.com/albertobsd/keysubtracter

Yup Thank you i found it rigtht after i posted this comment  !

**Comment by Pvnic** [comment]
> The program Don't do that sorry maybe you can find a solution with bash script or something like that

Thank you for replying man !
