### ISSUE TITLE
Core Dumped (segmentation fault) 

### ISSUE THREAD

**Issue by Pvnic** [albertobsd/ecctools#7]
Hello Alberto i'v been trying to use keydivision with an Input file but it seems to not work. The error i get doing it is in the title and the error i get with the compiler is this :

keydivision.c:167:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  167 |     fgets(buffer_input,1024,INPUT);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keydivision.c:206:6: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  206 |      fgets(buffer_input,1024,INPUT);
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -o keymath keymath.c gmpecc.o util.o  base58.o sha256.o rmd160.o -lgmp
rm *.o

Thank you !

**Comment by albertobsd** [comment]
Please add an screenshot

**Comment by Pvnic** [comment]
Sure thank you !
![1](https://user-images.githubusercontent.com/49695621/148243048-d7e3f3fc-c031-4e6c-86c1-c2630cc6c87d.png)
![2](https://user-images.githubusercontent.com/49695621/148243800-8a479aab-a3c0-4ead-b196-3dfc1b0a576e.png)

**Comment by albertobsd** [comment]
Solved in https://github.com/albertobsd/ecctools/commit/2ac5da0956a7a05441d2acc1a330e65b899deb10
