### ISSUE TITLE
keydivision -i file

### ISSUE THREAD

**Issue by Totulik** [albertobsd/ecctools#8]
Tell me how to use it. Command in the terminal. What should be in the file? Error - Segmentation fault.
./keydivision 
-i file         Input file, input file with public keys to be divided-o file            
Output file, if you omit this option the out will go to the standar output

**Comment by albertobsd** [comment]
Solved in https://github.com/albertobsd/ecctools/commit/2ac5da0956a7a05441d2acc1a330e65b899deb10
