### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by ET2200** [albertobsd/ecctools#9]
gcc -O3 -c bloom/bloom.c -o bloom.o
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
gcc -O3 -c gmpecc.c -o gmpecc.o
gmpecc.c:1:10: fatal error: gmp.h: No such file or directory
    1 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:7: default] Error 1

**Comment by albertobsd** [comment]
Google: "fatal error: gmp.h: No such file or directory"

**Comment by ET2200** [comment]
where file gmp.h ?

**Comment by ET2200** [comment]
Where file gmp.h ?

Pada tanggal Jum, 11 Feb 2022 pukul 12.47 Luis Alberto <
***@***.***> menulis:

**Comment by albertobsd** [comment]
Did you Google it? You need to install libgmpdev
